### PR TITLE
Add Token Management to the user-management-page

### PR DESCRIPTION
**Pull request by umesh-timalsina**
This is probably going to cause some merge conflicts, however, this feature branch was added created off from upstream and the dist files in master branch should be recreated and commited after merging this PR.

### CODE REVIEW

**Review by kecso — CHANGES_REQUESTED** [review]
It seems to be somewhat incomplete.
There is a single button for creating.
The first token created has a visible id, while all others are hidden as passwords.
- we need to be able to delete/regenerate tokens
- though the feature is not yet merged, there is a displayName for the token, so I believe we should take that into account as well
- if we follow the token logic, the id should not be shown at all, instead when generated there should be a single pop-up window/dialog that shows the id, but once that is closed, the user should only be able to regenerate it...
- also, I thought the token will have their own page (although they can exist here for now)
+1 although I understood that this feature is developed as a necessity for deep-forge, with such huge PRs it would be nicer to create a branch at the source (I can give you access to it), as this makes review very hard for someone not familiar with the changes made specifically for deep-forge.

let me know if you need help!

**Comment by umesh-timalsina** [comment]
@kecso Thanks for your suggestions.
1. This branch was setup to track upstream's master and has no deep-forge specific features. However, I can push to upstream if provided the access.
2. There's a delete icon on the token display table that allows you to delete tokens.
3. A popup or Modal should be easy to incorporate instead of Using `*******` to hide token Ids.
4. I was thinking the `Name` column in the current table should be incorporate the token DisplayName and have some `dblclick` event handler. Or, as you suggested if we have a separate page for this.

**Review by brollb — CHANGES_REQUESTED** [review]
Looks good! Here are my thoughts:
- It might be more clear to say "Access Tokens" instead of "Tokens" in the sidebar menu and the title for the page.
- "DisplayName" is not one word in the "Generate Tokens" modal. It might be nice to just say "Token Name" rather than "DisplayName". This would make the creation dialog consistent with the next one, too. Also, "Generate Tokens" - the header for that modal - could just say "Generate a new access token". Not to nit-pick but it only generates a single token.
- It currently says "Bad Request" when trying to create a token with a duplicate name. This is not actually an issue with this code as it seems the error message is lost somehow from the server (we talked about it earlier). Doesn't need a fix here but is a general issue.
- It might be nice to move "Token ID will only be displayed once" to be at the bottom where it would be closer to the actual ID.

**Review by brollb — APPROVED** [review]
LGTM. Nice work.

**Pull request merged**
